/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Ramith Gunawardana
 */
public class LoadingUI extends javax.swing.JFrame {

    /**
     * Creates new form LoadingUI
     */
    public LoadingUI() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/icon.png"));
        this.setIconImage(icon.getImage());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPercentatge = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_large.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 60, 400, 90);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Loading...");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 270, 74, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Management System");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 200, 400, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Time Table");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 170, 400, 20);

        lblPercentatge.setForeground(new java.awt.Color(255, 255, 255));
        lblPercentatge.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPercentatge.setText("0%");
        getContentPane().add(lblPercentatge);
        lblPercentatge.setBounds(350, 270, 45, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/load.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 290);

        progressBar.setBorder(null);
        getContentPane().add(progressBar);
        progressBar.setBounds(-10, 280, 420, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
            /* Create and display the form */
//        final int percentage = 50;
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                
////                try {
////                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
////                } catch (ClassNotFoundException ex) {
////                    Logger.getLogger(LoadingUI.class.getName()).log(Level.SEVERE, null, ex);
////                } catch (InstantiationException ex) {
////                    Logger.getLogger(LoadingUI.class.getName()).log(Level.SEVERE, null, ex);
////                } catch (IllegalAccessException ex) {
////                    Logger.getLogger(LoadingUI.class.getName()).log(Level.SEVERE, null, ex);
////                } catch (UnsupportedLookAndFeelException ex) {
////                    Logger.getLogger(LoadingUI.class.getName()).log(Level.SEVERE, null, ex);
////                }
//
////                LoadingUI frame = new LoadingUI();
////                frame.setVisible(true);
////                UIManager.put("ProgressBar.background", Color.BLACK);
////                UIManager.put("ProgressBar.foreground", Color.RED);
////                frame.lblPercentatge.setText(percentage + "%");
////                frame.progressBar.setValue(percentage);
//
//            }
//        });
            try {
                UIManager.setLookAndFeel(new FlatDarkLaf());
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(LoadingUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            LoadingUI frame = new LoadingUI();
            frame.setVisible(true);
            try{
                for(int i=0; i<101; i++){
                    Thread.sleep(20);
                    frame.progressBar.setForeground(new Color(1,174,209));
                    frame.lblPercentatge.setText(i + "%");
                    frame.progressBar.setValue(i);
                }
            }catch(InterruptedException e){
                System.out.println("Error: " +e);
            }
            frame.setVisible(false);
            
            SignInUI sign = new SignInUI();
            sign.setResizable(false);
            sign.setLocationRelativeTo(null);
            sign.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblPercentatge;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
